name: Generate Metrics
on:
  # Update automatically every 24 hours
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          # You can customize these plugins based on the screenshot
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_followup: yes
          plugin_followup_sections: repositories

      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_sections: most-used, recently-used
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_skyline: yes
          plugin_skyline_year: 2020
