name: Generate Metrics
on:
  # Update automatically every 24 hours
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          # You can customize these plugins based on the screenshot
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_followup: yes
          plugin_followup_sections: repositories

      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-right-1.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_repositories: yes
          plugin_repositories_featured: katto-1204/katto-1204

      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-right-2.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_skyline: yes
          plugin_skyline_year: 2020

      - name: Install GitHub Skyline Extension
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh extension install github/gh-skyline

      - name: GitHub City
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-right-3.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2020
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
